// Please don't change this file
  // It's generated by scripts/generators/conjugations.ts
  
  const verbs = [
  {
    word: "abhauen",
    type: "regular"
  },
  {
    word: "abholen",
    type: "regular"
  },
  {
    word: "abschließen",
    type: "regular"
  },
  {
    word: "akzeptieren",
    type: "regular"
  },
  {
    word: "ändern",
    type: "regular"
  },
  {
    word: "anfangen",
    type: "regular"
  },
  {
    word: "angehen",
    type: "regular"
  },
  {
    word: "angreifen",
    type: "regular"
  },
  {
    word: "ankommen",
    type: "regular"
  },
  {
    word: "annehmen",
    type: "regular"
  },
  {
    word: "anrufen",
    type: "regular"
  },
  {
    word: "antworten",
    type: "regular"
  },
  {
    word: "arbeiten",
    type: "regular"
  },
  {
    word: "aufgeben",
    type: "regular"
  },
  {
    word: "aufhalten",
    type: "regular"
  },
  {
    word: "aufhören",
    type: "regular"
  },
  {
    word: "aufnehmen",
    type: "regular"
  },
  {
    word: "aufpassen",
    type: "regular"
  },
  {
    word: "aufregen",
    type: "regular"
  },
  {
    word: "ausgehen",
    type: "regular"
  },
  {
    word: "aussehen",
    type: "regular"
  },
  {
    word: "bauen",
    type: "regular"
  },
  {
    word: "bedeuten",
    type: "regular"
  },
  {
    word: "beeilen",
    type: "regular"
  },
  {
    word: "beenden",
    type: "regular"
  },
  {
    word: "befehlen",
    type: "irregular"
  },
  {
    word: "befinden",
    type: "regular"
  },
  {
    word: "befreien",
    type: "regular"
  },
  {
    word: "begegnen",
    type: "regular"
  },
  {
    word: "beginnen",
    type: "irregular"
  },
  {
    word: "begleiten",
    type: "regular"
  },
  {
    word: "behalten",
    type: "regular"
  },
  {
    word: "behandeln",
    type: "regular"
  },
  {
    word: "beißen",
    type: "irregular"
  },
  {
    word: "bekommen",
    type: "regular"
  },
  {
    word: "bemerken",
    type: "regular"
  },
  {
    word: "benutzen",
    type: "regular"
  },
  {
    word: "beobachten",
    type: "regular"
  },
  {
    word: "beschäftigen",
    type: "regular"
  },
  {
    word: "beschreiben",
    type: "irregular"
  },
  {
    word: "beschützen",
    type: "regular"
  },
  {
    word: "besorgen",
    type: "regular"
  },
  {
    word: "besprechen",
    type: "regular"
  },
  {
    word: "bestehen",
    type: "regular"
  },
  {
    word: "bestimmen",
    type: "regular"
  },
  {
    word: "besuchen",
    type: "regular"
  },
  {
    word: "betreffen",
    type: "regular"
  },
  {
    word: "betrinken",
    type: "regular"
  },
  {
    word: "bewegen",
    type: "regular"
  },
  {
    word: "beweisen",
    type: "regular"
  },
  {
    word: "bezahlen",
    type: "regular"
  },
  {
    word: "bieten",
    type: "irregular"
  },
  {
    word: "binden",
    type: "irregular"
  },
  {
    word: "bitten",
    type: "regular"
  },
  {
    word: "bleiben",
    type: "irregular"
  },
  {
    word: "brauchen",
    type: "regular"
  },
  {
    word: "brechen",
    type: "irregular"
  },
  {
    word: "bringen",
    type: "regular"
  },
  {
    word: "danken",
    type: "regular"
  },
  {
    word: "dauern",
    type: "regular"
  },
  {
    word: "denken",
    type: "regular"
  },
  {
    word: "drehen",
    type: "regular"
  },
  {
    word: "dürfen",
    type: "irregular"
  },
  {
    word: "einladen",
    type: "regular"
  },
  {
    word: "empfangen",
    type: "irregular"
  },
  {
    word: "empfehlen",
    type: "irregular"
  },
  {
    word: "empfinden",
    type: "irregular"
  },
  {
    word: "enden",
    type: "regular"
  },
  {
    word: "entdecken",
    type: "regular"
  },
  {
    word: "entfernen",
    type: "regular"
  },
  {
    word: "entführen",
    type: "regular"
  },
  {
    word: "entkommen",
    type: "regular"
  },
  {
    word: "entlassen",
    type: "regular"
  },
  {
    word: "entscheiden",
    type: "regular"
  },
  {
    word: "entschuldigen",
    type: "regular"
  },
  {
    word: "enttäuschen",
    type: "regular"
  },
  {
    word: "entwickeln",
    type: "regular"
  },
  {
    word: "erfahren",
    type: "regular"
  },
  {
    word: "ergeben",
    type: "regular"
  },
  {
    word: "erhalten",
    type: "regular"
  },
  {
    word: "erinnern",
    type: "regular"
  },
  {
    word: "erkennen",
    type: "regular"
  },
  {
    word: "erklären",
    type: "regular"
  },
  {
    word: "erlauben",
    type: "regular"
  },
  {
    word: "erledigen",
    type: "regular"
  },
  {
    word: "ermorden",
    type: "regular"
  },
  {
    word: "erreichen",
    type: "regular"
  },
  {
    word: "erschießen",
    type: "regular"
  },
  {
    word: "erschrecken",
    type: "irregular"
  },
  {
    word: "ertragen",
    type: "regular"
  },
  {
    word: "erwachsen",
    type: "regular"
  },
  {
    word: "erwähnen",
    type: "regular"
  },
  {
    word: "erwarten",
    type: "regular"
  },
  {
    word: "erwischen",
    type: "regular"
  },
  {
    word: "erzählen",
    type: "regular"
  },
  {
    word: "erziehen",
    type: "irregular"
  },
  {
    word: "essen",
    type: "irregular"
  },
  {
    word: "existieren",
    type: "regular"
  },
  {
    word: "fahren",
    type: "irregular"
  },
  {
    word: "fallen",
    type: "irregular"
  },
  {
    word: "fangen",
    type: "irregular"
  },
  {
    word: "fassen",
    type: "regular"
  },
  {
    word: "fehlen",
    type: "regular"
  },
  {
    word: "fernsehen",
    type: "irregular"
  },
  {
    word: "feuern",
    type: "regular"
  },
  {
    word: "finden",
    type: "irregular"
  },
  {
    word: "fliegen",
    type: "irregular"
  },
  {
    word: "fliehen",
    type: "irregular"
  },
  {
    word: "fließen",
    type: "irregular"
  },
  {
    word: "folgen",
    type: "regular"
  },
  {
    word: "fragen",
    type: "regular"
  },
  {
    word: "freuen",
    type: "regular"
  },
  {
    word: "frieren",
    type: "irregular"
  },
  {
    word: "fühlen",
    type: "regular"
  },
  {
    word: "führen",
    type: "regular"
  },
  {
    word: "funktionieren",
    type: "regular"
  },
  {
    word: "fürchten",
    type: "regular"
  },
  {
    word: "gebären",
    type: "regular"
  },
  {
    word: "geben",
    type: "irregular"
  },
  {
    word: "gebrauchen",
    type: "regular"
  },
  {
    word: "gefallen",
    type: "irregular"
  },
  {
    word: "gehen",
    type: "irregular"
  },
  {
    word: "gehören",
    type: "regular"
  },
  {
    word: "gelingen",
    type: "irregular"
  },
  {
    word: "gelten",
    type: "regular"
  },
  {
    word: "genießen",
    type: "irregular"
  },
  {
    word: "geraten",
    type: "regular"
  },
  {
    word: "geschehen",
    type: "irregular"
  },
  {
    word: "gewinnen",
    type: "irregular"
  },
  {
    word: "gießen",
    type: "irregular"
  },
  {
    word: "glauben",
    type: "regular"
  },
  {
    word: "gleichen",
    type: "irregular"
  },
  {
    word: "greifen",
    type: "irregular"
  },
  {
    word: "haben",
    type: "irregular"
  },
  {
    word: "halten",
    type: "irregular"
  },
  {
    word: "hängen",
    type: "irregular"
  },
  {
    word: "hassen",
    type: "regular"
  },
  {
    word: "heiraten",
    type: "regular"
  },
  {
    word: "heißen",
    type: "irregular"
  },
  {
    word: "helfen",
    type: "irregular"
  },
  {
    word: "hingehen",
    type: "regular"
  },
  {
    word: "hinterlassen",
    type: "regular"
  },
  {
    word: "hoffen",
    type: "regular"
  },
  {
    word: "holen",
    type: "regular"
  },
  {
    word: "hören",
    type: "regular"
  },
  {
    word: "irren",
    type: "regular"
  },
  {
    word: "jagen",
    type: "regular"
  },
  {
    word: "kämpfen",
    type: "regular"
  },
  {
    word: "kapieren",
    type: "regular"
  },
  {
    word: "kaufen",
    type: "regular"
  },
  {
    word: "kennen",
    type: "regular"
  },
  {
    word: "klappen",
    type: "regular"
  },
  {
    word: "klauen",
    type: "regular"
  },
  {
    word: "klingen",
    type: "regular"
  },
  {
    word: "kommen",
    type: "irregular"
  },
  {
    word: "können",
    type: "irregular"
  },
  {
    word: "kontrollieren",
    type: "regular"
  },
  {
    word: "konzentrieren",
    type: "regular"
  },
  {
    word: "kriechen",
    type: "irregular"
  },
  {
    word: "kriegen",
    type: "regular"
  },
  {
    word: "kümmern",
    type: "regular"
  },
  {
    word: "küssen",
    type: "regular"
  },
  {
    word: "lachen",
    type: "regular"
  },
  {
    word: "laden",
    type: "irregular"
  },
  {
    word: "landen",
    type: "regular"
  },
  {
    word: "lassen",
    type: "irregular"
  },
  {
    word: "laufen",
    type: "irregular"
  },
  {
    word: "lauten",
    type: "regular"
  },
  {
    word: "leben",
    type: "regular"
  },
  {
    word: "legen",
    type: "regular"
  },
  {
    word: "leiden",
    type: "irregular"
  },
  {
    word: "leihen",
    type: "irregular"
  },
  {
    word: "leisten",
    type: "regular"
  },
  {
    word: "lernen",
    type: "regular"
  },
  {
    word: "lesen",
    type: "irregular"
  },
  {
    word: "lieben",
    type: "regular"
  },
  {
    word: "liegen",
    type: "irregular"
  },
  {
    word: "lösen",
    type: "regular"
  },
  {
    word: "lügen",
    type: "irregular"
  },
  {
    word: "machen",
    type: "regular"
  },
  {
    word: "meinen",
    type: "regular"
  },
  {
    word: "melden",
    type: "regular"
  },
  {
    word: "merken",
    type: "regular"
  },
  {
    word: "mitbringen",
    type: "regular"
  },
  {
    word: "mitkommen",
    type: "regular"
  },
  {
    word: "mitnehmen",
    type: "regular"
  },
  {
    word: "mögen",
    type: "irregular"
  },
  {
    word: "müssen",
    type: "irregular"
  },
  {
    word: "nachdenken",
    type: "regular"
  },
  {
    word: "nehmen",
    type: "irregular"
  },
  {
    word: "nennen",
    type: "regular"
  },
  {
    word: "öffnen",
    type: "regular"
  },
  {
    word: "passen",
    type: "regular"
  },
  {
    word: "passieren",
    type: "regular"
  },
  {
    word: "pfeifen",
    type: "irregular"
  },
  {
    word: "planen",
    type: "regular"
  },
  {
    word: "raten",
    type: "irregular"
  },
  {
    word: "rauchen",
    type: "regular"
  },
  {
    word: "reden",
    type: "regular"
  },
  {
    word: "reißen",
    type: "irregular"
  },
  {
    word: "reiten",
    type: "irregular"
  },
  {
    word: "reparieren",
    type: "regular"
  },
  {
    word: "retten",
    type: "regular"
  },
  {
    word: "riechen",
    type: "irregular"
  },
  {
    word: "riskieren",
    type: "regular"
  },
  {
    word: "rufen",
    type: "irregular"
  },
  {
    word: "sagen",
    type: "regular"
  },
  {
    word: "schaffen",
    type: "regular"
  },
  {
    word: "schätzen",
    type: "regular"
  },
  {
    word: "schauen",
    type: "regular"
  },
  {
    word: "scheinen",
    type: "irregular"
  },
  {
    word: "schicken",
    type: "regular"
  },
  {
    word: "schieben",
    type: "irregular"
  },
  {
    word: "schießen",
    type: "irregular"
  },
  {
    word: "schlafen",
    type: "irregular"
  },
  {
    word: "schlagen",
    type: "irregular"
  },
  {
    word: "schließen",
    type: "irregular"
  },
  {
    word: "schmecken",
    type: "regular"
  },
  {
    word: "schneiden",
    type: "irregular"
  },
  {
    word: "schreiben",
    type: "irregular"
  },
  {
    word: "schreien",
    type: "irregular"
  },
  {
    word: "schreiten",
    type: "irregular"
  },
  {
    word: "schützen",
    type: "regular"
  },
  {
    word: "schweigen",
    type: "irregular"
  },
  {
    word: "schwimmen",
    type: "irregular"
  },
  {
    word: "schwören",
    type: "regular"
  },
  {
    word: "sehen",
    type: "irregular"
  },
  {
    word: "sein",
    type: "irregular"
  },
  {
    word: "setzen",
    type: "regular"
  },
  {
    word: "singen",
    type: "irregular"
  },
  {
    word: "sinken",
    type: "irregular"
  },
  {
    word: "sitzen",
    type: "irregular"
  },
  {
    word: "sollen",
    type: "irregular"
  },
  {
    word: "sorgen",
    type: "regular"
  },
  {
    word: "spielen",
    type: "regular"
  },
  {
    word: "sprechen",
    type: "irregular"
  },
  {
    word: "springen",
    type: "irregular"
  },
  {
    word: "spüren",
    type: "regular"
  },
  {
    word: "stammen",
    type: "regular"
  },
  {
    word: "starten",
    type: "regular"
  },
  {
    word: "stecken",
    type: "regular"
  },
  {
    word: "stehen",
    type: "irregular"
  },
  {
    word: "stehlen",
    type: "irregular"
  },
  {
    word: "steigen",
    type: "irregular"
  },
  {
    word: "stellen",
    type: "regular"
  },
  {
    word: "sterben",
    type: "irregular"
  },
  {
    word: "stimmen",
    type: "regular"
  },
  {
    word: "stoppen",
    type: "regular"
  },
  {
    word: "stören",
    type: "regular"
  },
  {
    word: "streiten",
    type: "irregular"
  },
  {
    word: "suchen",
    type: "regular"
  },
  {
    word: "tanzen",
    type: "regular"
  },
  {
    word: "teilen",
    type: "regular"
  },
  {
    word: "töten",
    type: "regular"
  },
  {
    word: "tragen",
    type: "irregular"
  },
  {
    word: "trauen",
    type: "regular"
  },
  {
    word: "treffen",
    type: "irregular"
  },
  {
    word: "trennen",
    type: "regular"
  },
  {
    word: "treten",
    type: "irregular"
  },
  {
    word: "trinken",
    type: "irregular"
  },
  {
    word: "trügen",
    type: "irregular"
  },
  {
    word: "tun",
    type: "irregular"
  },
  {
    word: "übergeben",
    type: "regular"
  },
  {
    word: "überleben",
    type: "regular"
  },
  {
    word: "überlegen",
    type: "regular"
  },
  {
    word: "übernehmen",
    type: "regular"
  },
  {
    word: "überprüfen",
    type: "regular"
  },
  {
    word: "überraschen",
    type: "regular"
  },
  {
    word: "überzeugen",
    type: "regular"
  },
  {
    word: "umbringen",
    type: "regular"
  },
  {
    word: "umgehen",
    type: "regular"
  },
  {
    word: "unterbrechen",
    type: "irregular"
  },
  {
    word: "unterhalten",
    type: "regular"
  },
  {
    word: "unternehmen",
    type: "irregular"
  },
  {
    word: "verändern",
    type: "regular"
  },
  {
    word: "verbieten",
    type: "irregular"
  },
  {
    word: "verbinden",
    type: "regular"
  },
  {
    word: "verbringen",
    type: "regular"
  },
  {
    word: "verdammen",
    type: "regular"
  },
  {
    word: "verderben",
    type: "irregular"
  },
  {
    word: "verdienen",
    type: "regular"
  },
  {
    word: "verfolgen",
    type: "regular"
  },
  {
    word: "vergeben",
    type: "regular"
  },
  {
    word: "vergessen",
    type: "irregular"
  },
  {
    word: "verhaften",
    type: "regular"
  },
  {
    word: "verheiraten",
    type: "regular"
  },
  {
    word: "verhindern",
    type: "regular"
  },
  {
    word: "verkaufen",
    type: "regular"
  },
  {
    word: "verlangen",
    type: "regular"
  },
  {
    word: "verlassen",
    type: "irregular"
  },
  {
    word: "verletzen",
    type: "regular"
  },
  {
    word: "verlieben",
    type: "regular"
  },
  {
    word: "verlieren",
    type: "irregular"
  },
  {
    word: "vermeiden",
    type: "irregular"
  },
  {
    word: "vermissen",
    type: "regular"
  },
  {
    word: "vernichten",
    type: "regular"
  },
  {
    word: "verpassen",
    type: "regular"
  },
  {
    word: "verraten",
    type: "regular"
  },
  {
    word: "verschwinden",
    type: "regular"
  },
  {
    word: "versprechen",
    type: "regular"
  },
  {
    word: "verstecken",
    type: "regular"
  },
  {
    word: "verstehen",
    type: "regular"
  },
  {
    word: "versuchen",
    type: "regular"
  },
  {
    word: "vertrauen",
    type: "regular"
  },
  {
    word: "verursachen",
    type: "regular"
  },
  {
    word: "verzeihen",
    type: "irregular"
  },
  {
    word: "vorbereiten",
    type: "regular"
  },
  {
    word: "vorstellen",
    type: "regular"
  },
  {
    word: "wachsen",
    type: "irregular"
  },
  {
    word: "wählen",
    type: "regular"
  },
  {
    word: "wahren",
    type: "regular"
  },
  {
    word: "warten",
    type: "regular"
  },
  {
    word: "waschen",
    type: "irregular"
  },
  {
    word: "weichen",
    type: "irregular"
  },
  {
    word: "weinen",
    type: "regular"
  },
  {
    word: "weitermachen",
    type: "regular"
  },
  {
    word: "werben",
    type: "irregular"
  },
  {
    word: "werden",
    type: "irregular"
  },
  {
    word: "werfen",
    type: "irregular"
  },
  {
    word: "wetten",
    type: "regular"
  },
  {
    word: "wiegen",
    type: "irregular"
  },
  {
    word: "wissen",
    type: "irregular"
  },
  {
    word: "wohnen",
    type: "regular"
  },
  {
    word: "wollen",
    type: "irregular"
  },
  {
    word: "wringen",
    type: "irregular"
  },
  {
    word: "wünschen",
    type: "regular"
  },
  {
    word: "zahlen",
    type: "regular"
  },
  {
    word: "zählen",
    type: "regular"
  },
  {
    word: "zeigen",
    type: "regular"
  },
  {
    word: "zerstören",
    type: "regular"
  },
  {
    word: "ziehen",
    type: "irregular"
  },
  {
    word: "zuhören",
    type: "regular"
  },
  {
    word: "zulassen",
    type: "regular"
  },
  {
    word: "zurückkommen",
    type: "regular"
  },
  {
    word: "zwingen",
    type: "irregular"
  }
];
  
  export default verbs;