import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, ButtonGroup } from '@chakra-ui/react'
import useSWR from 'swr'
// @ts-ignore
const fetcher = (...args) => fetch(...args).then(res => res.json())
const verbs = [
    {
        verb: "finden",
        stem: "find",
        forms: [
            "finde",
            "findest",
            "findet",
            "finden",
            "findet",
            "finden"
        ]
    }
]

type ConjugationTrainerProps = {
  word: string;
}

function useWord(word: string) {
  const { data, error } = useSWR(() => {
      return `/words/${word}.json`
  }, fetcher);

  return {
    error,
    isLoading: !error && !data,
    word: data
  }
}

type SelectButtonProps = {
  endings: string[];
}

function SelectButton({ endings }: SelectButtonProps) {
  return <ButtonGroup isAttached>
    {endings.map(end => <Button key={end}>{end}</Button>)}
  </ButtonGroup>
}

function ConjugationTrainer({ word }: ConjugationTrainerProps) {
  const { error, isLoading, word: wordInfo } = useWord(word);

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>

  return <div>
    Verb: {wordInfo.infinitive}<br /><br />

    Ich {wordInfo.stem} <SelectButton endings={['-e', '-en', '-st']} /> <br /> 
    Du {wordInfo.stem} <SelectButton endings={['-e', '-en', '-st']} /> <br /> 
    Er/Sie/Es {wordInfo.stem}<SelectButton endings={['-e', '-en', '-st']} /> <br /> 
    Wir {wordInfo.stem}<SelectButton endings={['-e', '-en', '-st']} /> <br /> 
    Ihr {wordInfo.stem}<SelectButton endings={['-e', '-en', '-st']} /> <br /> 
    sie/Sie {wordInfo.stem}<SelectButton endings={['-e', '-en', '-st']} /> <br /> 
  </div>
}

export default function Trainer() {
  const { data: words, error } = useSWR('/words/index.json', fetcher)

  if (error) return <div>failed to load</div>
  if (!words) return <div>loading...</div>

  const verb = words[Math.floor(Math.random()*words.length)]

  return (
    <div className={styles.container}>
      <Head>
        <title>Conjugation Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConjugationTrainer word={verb.infinitive} />
    </div>
  )
}
