import Head from "next/head";
import React from "react";
import ExerciseCard from "../../components/ExerciseCard";

export default function Trainer() {
  return (
    <div>
      <Head>
        <title>Excercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ExerciseCard
        title="Conjugator"
        href="/exercises/conjugator"
        description="Present tense conjugation practice for regular verbs."
      />
    </div>
  );
}
